name: star_wars_rpg
description: "Star Wars RPG — jeu de plateau RPG numérique au tour par tour (Sprint 1)."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter

  # Gestion d'état (Architecture v1.0)
  flutter_riverpod: ^2.6.1

  # Navigation (Architecture v1.0)
  go_router: ^14.8.1

  # Sauvegarde locale (Architecture v1.0)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/music/accueil/
    - assets/audio/music/combats/
    - assets/audio/music/credits/
    - assets/audio/music/fin_lumineuse/
    - assets/audio/music/fin_sombre/
    - assets/audio/music/lieux/
    - assets/audio/music/parametres/
    - assets/audio/music/planetes/
    - assets/audio/music/preparation/
    - assets/audio/sfx/
    - assets/images/allies/
    - assets/images/allies/healers/
    - assets/images/allies/nukers/
    - assets/images/allies/specials/
    - assets/images/allies/squads/
    - assets/images/allies/supports/
    - assets/images/allies/tanks/
    - assets/images/armors/
    - assets/images/bosses/
    - assets/images/cantina/
    - assets/images/characters/
    - assets/images/monsters/
    - assets/images/planets/
    - assets/images/screens/
    - assets/images/screens/credits/
    - assets/images/screens/game_over/
    - assets/images/screens/parametres/
    - assets/images/weapons/
